spring:
  profiles:
    default: "dev"
  application:
    name: Backend
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/flight_ticket_application_2?serverTimezone=UTC
    username: root
    password: TOmi1970
server:
  port: 81
backendUri: http://localhost:83/datetimedata
---
spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_ROOT_PASSWORD}
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
      formar_sql: true
  config:
    activate:
      on-profile: dockerized
server:
  port: 8081
#show sql statement
logging:

  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace